name: Deploy to Emsio Servers
description: Deploys the application to Emsio servers using the deploy endpoint.
author: Stanislav Škudrna
branding:
  color: blue
  icon: upload-cloud

inputs:
  app_secret:
    description: Deployment token for authentication.
    required: true

runs:
  using: composite
  steps:
    - name: Deploy to server
      shell: bash
      run: |
        set -euo pipefail

        curl -sS -f \
          -X POST "https://deploy.emsio.cz/ghad/df/v4/run" \
          -H "Authorization: Bearer ${{ inputs.app_secret }}" \
          -H "X-SHA: ${{ github.sha }}"